// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.DAL.Data;

#nullable disable

namespace User.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515155825_SeedingDatabase")]
    partial class SeedingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("User.DAL.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("User.DAL.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("User.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN1",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 84.189999999999998,
                            Price = 400.12,
                            Title = "BookTitle1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN2",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 28.039999999999999,
                            Price = 233.44,
                            Title = "BookTitle2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN3",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 10.57,
                            Price = 234.75,
                            Title = "BookTitle3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN4",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 52.960000000000001,
                            Price = 251.75,
                            Title = "BookTitle4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN5",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 33.32,
                            Price = 449.39999999999998,
                            Title = "BookTitle5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN6",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 149.19,
                            Price = 421.43000000000001,
                            Title = "BookTitle6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN7",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 71.540000000000006,
                            Price = 395.69,
                            Title = "BookTitle7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN8",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 20.59,
                            Price = 275.26999999999998,
                            Title = "BookTitle8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN9",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 41.789999999999999,
                            Price = 224.06,
                            Title = "BookTitle9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN10",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 40.990000000000002,
                            Price = 150.05000000000001,
                            Title = "BookTitle10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN11",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 85.519999999999996,
                            Price = 281.04000000000002,
                            Title = "BookTitle11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN12",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 80.260000000000005,
                            Price = 231.59999999999999,
                            Title = "BookTitle12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN13",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 139.43000000000001,
                            Price = 426.54000000000002,
                            Title = "BookTitle13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN14",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 109.23999999999999,
                            Price = 251.18000000000001,
                            Title = "BookTitle14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN15",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 22.199999999999999,
                            Price = 434.38999999999999,
                            Title = "BookTitle15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN16",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 141.46000000000001,
                            Price = 423.32999999999998,
                            Title = "BookTitle16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN17",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 134.31,
                            Price = 203.41,
                            Title = "BookTitle17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN18",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 35.899999999999999,
                            Price = 223.18000000000001,
                            Title = "BookTitle18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN19",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 52.990000000000002,
                            Price = 494.82999999999998,
                            Title = "BookTitle19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN20",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 114.44,
                            Price = 440.13999999999999,
                            Title = "BookTitle20"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN21",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 132.83000000000001,
                            Price = 491.69,
                            Title = "BookTitle21"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN22",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 24.359999999999999,
                            Price = 325.68000000000001,
                            Title = "BookTitle22"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN23",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 45.030000000000001,
                            Price = 163.69,
                            Title = "BookTitle23"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN24",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 11.84,
                            Price = 348.45999999999998,
                            Title = "BookTitle24"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN25",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 120.45,
                            Price = 371.33999999999997,
                            Title = "BookTitle25"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN26",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 79.849999999999994,
                            Price = 272.17000000000002,
                            Title = "BookTitle26"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN27",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 82.659999999999997,
                            Price = 345.87,
                            Title = "BookTitle27"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN28",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 103.41,
                            Price = 476.10000000000002,
                            Title = "BookTitle28"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN29",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 108.98,
                            Price = 152.72,
                            Title = "BookTitle29"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN30",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 83.219999999999999,
                            Price = 221.13,
                            Title = "BookTitle30"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN31",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 143.78,
                            Price = 221.0,
                            Title = "BookTitle31"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN32",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 38.990000000000002,
                            Price = 366.72000000000003,
                            Title = "BookTitle32"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN33",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 122.75,
                            Price = 418.91000000000003,
                            Title = "BookTitle33"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN34",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 20.739999999999998,
                            Price = 151.25,
                            Title = "BookTitle34"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN35",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 99.019999999999996,
                            Price = 374.36000000000001,
                            Title = "BookTitle35"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN36",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 114.28,
                            Price = 481.06,
                            Title = "BookTitle36"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN37",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 111.37,
                            Price = 437.81999999999999,
                            Title = "BookTitle37"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN38",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 16.57,
                            Price = 218.38,
                            Title = "BookTitle38"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN39",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 35.93,
                            Price = 388.29000000000002,
                            Title = "BookTitle39"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN40",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 144.47999999999999,
                            Price = 420.11000000000001,
                            Title = "BookTitle40"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN41",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 51.450000000000003,
                            Price = 157.06,
                            Title = "BookTitle41"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN42",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 77.189999999999998,
                            Price = 188.43000000000001,
                            Title = "BookTitle42"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN43",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 128.49000000000001,
                            Price = 278.39999999999998,
                            Title = "BookTitle43"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN44",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 10.449999999999999,
                            Price = 213.21000000000001,
                            Title = "BookTitle44"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN45",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 58.140000000000001,
                            Price = 388.87,
                            Title = "BookTitle45"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN46",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 100.88,
                            Price = 207.90000000000001,
                            Title = "BookTitle46"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN47",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 114.06999999999999,
                            Price = 196.61000000000001,
                            Title = "BookTitle47"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN48",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 19.789999999999999,
                            Price = 414.61000000000001,
                            Title = "BookTitle48"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN49",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 131.25,
                            Price = 391.10000000000002,
                            Title = "BookTitle49"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN50",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 56.280000000000001,
                            Price = 229.78999999999999,
                            Title = "BookTitle50"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN51",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 71.829999999999998,
                            Price = 366.80000000000001,
                            Title = "BookTitle51"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN52",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 143.43000000000001,
                            Price = 181.09999999999999,
                            Title = "BookTitle52"
                        },
                        new
                        {
                            Id = 53,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN53",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 34.939999999999998,
                            Price = 390.37,
                            Title = "BookTitle53"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN54",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 108.08,
                            Price = 297.87,
                            Title = "BookTitle54"
                        },
                        new
                        {
                            Id = 55,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN55",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 12.300000000000001,
                            Price = 222.38999999999999,
                            Title = "BookTitle55"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN56",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 83.579999999999998,
                            Price = 245.28,
                            Title = "BookTitle56"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN57",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 20.370000000000001,
                            Price = 274.42000000000002,
                            Title = "BookTitle57"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN58",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 25.579999999999998,
                            Price = 390.19,
                            Title = "BookTitle58"
                        },
                        new
                        {
                            Id = 59,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN59",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 35.420000000000002,
                            Price = 259.98000000000002,
                            Title = "BookTitle59"
                        },
                        new
                        {
                            Id = 60,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN60",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 123.48999999999999,
                            Price = 249.36000000000001,
                            Title = "BookTitle60"
                        },
                        new
                        {
                            Id = 61,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN61",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 112.7,
                            Price = 299.24000000000001,
                            Title = "BookTitle61"
                        },
                        new
                        {
                            Id = 62,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN62",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 48.530000000000001,
                            Price = 261.16000000000003,
                            Title = "BookTitle62"
                        },
                        new
                        {
                            Id = 63,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN63",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 52.240000000000002,
                            Price = 319.45999999999998,
                            Title = "BookTitle63"
                        },
                        new
                        {
                            Id = 64,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN64",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 125.16,
                            Price = 394.94,
                            Title = "BookTitle64"
                        },
                        new
                        {
                            Id = 65,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN65",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 11.550000000000001,
                            Price = 392.97000000000003,
                            Title = "BookTitle65"
                        },
                        new
                        {
                            Id = 66,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN66",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 140.87,
                            Price = 459.27999999999997,
                            Title = "BookTitle66"
                        },
                        new
                        {
                            Id = 67,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN67",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 148.13,
                            Price = 343.86000000000001,
                            Title = "BookTitle67"
                        },
                        new
                        {
                            Id = 68,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN68",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 74.0,
                            Price = 443.41000000000003,
                            Title = "BookTitle68"
                        },
                        new
                        {
                            Id = 69,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN69",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 121.38,
                            Price = 393.70999999999998,
                            Title = "BookTitle69"
                        },
                        new
                        {
                            Id = 70,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN70",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 84.930000000000007,
                            Price = 364.64999999999998,
                            Title = "BookTitle70"
                        },
                        new
                        {
                            Id = 71,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN71",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 98.989999999999995,
                            Price = 331.63,
                            Title = "BookTitle71"
                        },
                        new
                        {
                            Id = 72,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN72",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 42.920000000000002,
                            Price = 423.43000000000001,
                            Title = "BookTitle72"
                        },
                        new
                        {
                            Id = 73,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN73",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 34.579999999999998,
                            Price = 313.12,
                            Title = "BookTitle73"
                        },
                        new
                        {
                            Id = 74,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN74",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 47.810000000000002,
                            Price = 492.29000000000002,
                            Title = "BookTitle74"
                        },
                        new
                        {
                            Id = 75,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN75",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 116.43000000000001,
                            Price = 495.93000000000001,
                            Title = "BookTitle75"
                        },
                        new
                        {
                            Id = 76,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN76",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 97.599999999999994,
                            Price = 189.50999999999999,
                            Title = "BookTitle76"
                        },
                        new
                        {
                            Id = 77,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN77",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 133.52000000000001,
                            Price = 479.56999999999999,
                            Title = "BookTitle77"
                        },
                        new
                        {
                            Id = 78,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN78",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 106.84999999999999,
                            Price = 414.22000000000003,
                            Title = "BookTitle78"
                        },
                        new
                        {
                            Id = 79,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN79",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 75.540000000000006,
                            Price = 326.63,
                            Title = "BookTitle79"
                        },
                        new
                        {
                            Id = 80,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN80",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 25.0,
                            Price = 280.97000000000003,
                            Title = "BookTitle80"
                        },
                        new
                        {
                            Id = 81,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN81",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 34.979999999999997,
                            Price = 296.60000000000002,
                            Title = "BookTitle81"
                        },
                        new
                        {
                            Id = 82,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN82",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 59.710000000000001,
                            Price = 259.79000000000002,
                            Title = "BookTitle82"
                        },
                        new
                        {
                            Id = 83,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN83",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 19.649999999999999,
                            Price = 298.56999999999999,
                            Title = "BookTitle83"
                        },
                        new
                        {
                            Id = 84,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN84",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 25.23,
                            Price = 499.68000000000001,
                            Title = "BookTitle84"
                        },
                        new
                        {
                            Id = 85,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN85",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 132.68000000000001,
                            Price = 395.36000000000001,
                            Title = "BookTitle85"
                        },
                        new
                        {
                            Id = 86,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN86",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 126.91,
                            Price = 355.19999999999999,
                            Title = "BookTitle86"
                        },
                        new
                        {
                            Id = 87,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN87",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 149.97999999999999,
                            Price = 430.99000000000001,
                            Title = "BookTitle87"
                        },
                        new
                        {
                            Id = 88,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN88",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 50.210000000000001,
                            Price = 151.16,
                            Title = "BookTitle88"
                        },
                        new
                        {
                            Id = 89,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN89",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 41.770000000000003,
                            Price = 396.47000000000003,
                            Title = "BookTitle89"
                        },
                        new
                        {
                            Id = 90,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN90",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 139.94,
                            Price = 274.37,
                            Title = "BookTitle90"
                        },
                        new
                        {
                            Id = 91,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN91",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 93.439999999999998,
                            Price = 237.25999999999999,
                            Title = "BookTitle91"
                        },
                        new
                        {
                            Id = 92,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN92",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 52.130000000000003,
                            Price = 159.53,
                            Title = "BookTitle92"
                        },
                        new
                        {
                            Id = 93,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN93",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 136.58000000000001,
                            Price = 393.58999999999997,
                            Title = "BookTitle93"
                        },
                        new
                        {
                            Id = 94,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN94",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 111.20999999999999,
                            Price = 297.56999999999999,
                            Title = "BookTitle94"
                        },
                        new
                        {
                            Id = 95,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN95",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 149.81999999999999,
                            Price = 387.45999999999998,
                            Title = "BookTitle95"
                        },
                        new
                        {
                            Id = 96,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN96",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 100.08,
                            Price = 203.13,
                            Title = "BookTitle96"
                        },
                        new
                        {
                            Id = 97,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN97",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 69.329999999999998,
                            Price = 456.38999999999999,
                            Title = "BookTitle97"
                        },
                        new
                        {
                            Id = 98,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN98",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 96.730000000000004,
                            Price = 287.75,
                            Title = "BookTitle98"
                        },
                        new
                        {
                            Id = 99,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN99",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 128.52000000000001,
                            Price = 253.65000000000001,
                            Title = "BookTitle99"
                        },
                        new
                        {
                            Id = 100,
                            Author = "Name1",
                            CategoryId = 1,
                            CompanyId = 1,
                            Description = "The book description goes most prominently on the back cover, and the top of your Amazon page (below the price and above the book reviews). It’s crucial it be compelling, because readers make buying decisions from the book description.",
                            ISBN = "ISBN100",
                            ImageUrl = "\\images\\products\\Book.png",
                            ListPrice = 108.25,
                            Price = 295.02999999999997,
                            Title = "BookTitle100"
                        });
                });

            modelBuilder.Entity("User.DAL.Models.Product", b =>
                {
                    b.HasOne("User.DAL.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.DAL.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("company");
                });
#pragma warning restore 612, 618
        }
    }
}
